name: Grep report
# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'grep-test.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  STATUS: 1
jobs:
  is_changed:
    runs-on: ubuntu-latest
    steps:
      # Checks-out current branch
      - uses: actions/checkout@v2
      - name: create git diff
        id: gitdif
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          git fetch origin main ${{ github.event.pull_request.base.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > gitdiff
          echo ::set-output name=diff::$(cat gitdiff)
          grep never_in_taxon gitdiff
      - name: cancel if condition met
        if: "!contains(${{ steps.gitdif.outputs.diff }}, mahmut)"
        run: |
          echo Taxon constraint updates do not exist
          echo "STATUS=0" >> $GITHUB_ENV
          echo $STATUS
      - name: if control
        run: |
          grep never_in_taxon ${{ steps.gitdif.outputs.diff }}
  grep_reporting:
    needs: is_changed
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: obolibrary/odklite:v1.2.32
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out current branch
      - uses: actions/checkout@v2
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - name: do something
        run: echo something
