# This is a basic workflow to help you get started with Actions

name: Diff report

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "taxon_reporting"
  taxon_reporting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: obolibrary/odklite:v1.2.32

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out current branch
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo ${{ github.ref }}
      # Runs a single command using the runners shell
      - name: list directory content - report
        run: |
          ls -l
          
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      
      # Runs a single command using the runners shell
      - name: list directory content - main
        run: |
          ls -l
          ls -l main
      # magic
      - name: magic test
        run: diff wine.owl main/wine.owl | grep German   
      # Runs a single command using the runners shell
      - name: robot report
        run: |
          pwd
          ls -l
          wget https://github.com/ontodev/robot/releases/download/v1.8.3/robot.jar
          curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot
          sudo chmod +x robot
          ls -l
          cp robot.jar /usr/local/bin/
          cp robot /usr/local/bin/
          robot diff --left wine.owl --right main/wine.owl > taxon_report.md
      - name: comment PR
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "taxon_report.md"
