# This is a basic workflow to help you get started with Actions

name: Diff report

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'wine.owl'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "taxon_reporting"
  taxon_reporting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: obolibrary/odklite:v1.2.32

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out current branch
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo ${{ github.ref }}
      # Runs a single command using the runners shell
      - name: list directory content - report
        run: |
          ls -l
          
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      
      # Runs a single command using the runners shell
      - name: list directory content - main
        run: |
          ls -l
          ls -l main
      # magic
      - name: magic test
        run: diff wine.owl main/wine.owl | grep German   
      # Runs a single command using the runners shell
      - name: robot report
        run: export ROBOT_JAVA_ARGS=-Xmx6G; robot diff --left wine.owl --right main/wine.owl > classification-diff.md
      - name: Upload diff
        uses: actions/upload-artifact@v2
        with:
          name: classification-diff.md
          path: classification-diff.md

  post_comment:
    needs: taxon_reporting
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Download diff
        uses: actions/download-artifact@v2
        with:
          name: classification-diff.md
          path: classification-diff.md
      - name: Prepare comment
        run: "echo \"Here's a diff of how these changes impact the classified ontology: \n\" >comment.md; cat classification-diff.md/classification-diff.md >>comment.md"
      - name: Post comment
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: cml-send-comment --update comment.md
