# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "taxon_reporting"
  taxon_reporting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: obolibrary/odkfull:v1.2.26

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out current branch
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo ${{ github.ref }}
      # Runs a single command using the runners shell
      - name: list directory content - report
        run: |
          ls -l
          pwd
          
      # Checks-out main branch under "main" directory
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      
      # Runs a single command using the runners shell
      - name: list directory content - main
        run: |
          ls -l
          ls -l main
          pwd
          
      # Runs a single command using the runners shell
      - name: robot report
        run: |
          pwd
          ls -l
          curl -H "Accept: application/zip" https://github.com/ontodev/robot/releases/download/v1.8.3/robot.jar -o robot.jar
          ls -l
          curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot
          ls -l
          sudo chmod +x robot
          ls -l
          robot diff --left wine.owl --right main-wine.owl
